"use client"
import React,{useState , useRef , useEffect} from 'react'

const contributions = [1,5,6,2,3,4,9,12,1,0,0,3];

const Landing5 = () => {
    const contributioncontainer = useRef(null);
    useEffect(() => {
        let container = contributioncontainer.current;
        let divs = Array.from(container.getElementsByTagName("div"));
        let max = Math.max(...contributions);
        for(let i = 0 ; i < contributions.length ; i++){
            let percent = contributions[i]/max;
            if(percent == 0){
                continue;
            }else if(percent <= 0.25){
                divs[i].classList.add("bg-green-300");
            }else if(percent <= 0.5){
                divs[i].classList.add("bg-green-400");
            }else if(percent <= 0.75){
                divs[i].classList.add("bg-green-600");
            }else{
                divs[i].classList.add("bg-green-800");
            }
        }
        // const handlemouseover = (e)=>{

        // }
        // container.addEventListener("mouseover" , (e)=>{
            
        // })
    
      return () => {
        
      }
    }, [])
    
    return (
        <>
            <section className='h-screen py-20 grid place-content-center' >
                <div className="innercontainer  ">
                    <h2>Contributions chart</h2>
                    <div ref={contributioncontainer} className='border rounded-sm p-2 grid grid-flow-col grid-rows-7 gap-1 w-fit' >
                    {/* <span className="skipboxtool"></span> */}
                    <div className="001  border p-1.5 w-1 rounded-sm"></div>
                    <div className="_1 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_2 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_3 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_4 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_5 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_6 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_7 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_8 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_9 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_10 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_11 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_12 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_13 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_14 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_15 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_16 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_17 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_18 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_19 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_20 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_21 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_22 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_23 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_24 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_25 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_26 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_27 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_28 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_29 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_30 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_31 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_32 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_33 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_34 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_35 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_36 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_37 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_38 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_39 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_40 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_41 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_42 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_43 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_44 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_45 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_46 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_47 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_48 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_49 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_50 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_51 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_52 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_53 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_54 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_55 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_56 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_57 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_58 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_59 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_60 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_61 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_62 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_63 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_64 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_65 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_66 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_67 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_68 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_69 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_70 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_71 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_72 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_73 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_74 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_75 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_76 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_77 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_78 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_79 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_80 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_81 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_82 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_83 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_84 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_85 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_86 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_87 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_88 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_89 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_90 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_91 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_92 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_93 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_94 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_95 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_96 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_97 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_98 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_99 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_100 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_101 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_102 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_103 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_104 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_105 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_106 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_107 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_108 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_109 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_110 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_111 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_112 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_113 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_114 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_115 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_116 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_117 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_118 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_119 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_120 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_121 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_122 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_123 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_124 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_125 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_126 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_127 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_128 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_129 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_130 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_131 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_132 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_133 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_134 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_135 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_136 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_137 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_138 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_139 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_140 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_141 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_142 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_143 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_144 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_145 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_146 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_147 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_148 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_149 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_150 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_151 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_152 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_153 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_154 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_155 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_156 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_157 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_158 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_159 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_160 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_161 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_162 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_163 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_164 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_165 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_166 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_167 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_168 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_169 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_170 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_171 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_172 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_173 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_174 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_175 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_176 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_177 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_178 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_179 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_180 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_181 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_182 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_183 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_184 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_185 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_186 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_187 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_188 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_189 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_190 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_191 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_192 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_193 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_194 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_195 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_196 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_197 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_198 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_199 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_200 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_201 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_202 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_203 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_204 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_205 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_206 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_207 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_208 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_209 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_210 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_211 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_212 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_213 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_214 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_215 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_216 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_217 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_218 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_219 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_220 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_221 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_222 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_223 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_224 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_225 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_226 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_227 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_228 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_229 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_230 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_231 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_232 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_233 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_234 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_235 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_236 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_237 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_238 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_239 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_240 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_241 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_242 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_243 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_244 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_245 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_246 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_247 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_248 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_249 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_250 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_251 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_252 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_253 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_254 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_255 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_256 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_257 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_258 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_259 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_260 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_261 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_262 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_263 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_264 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_265 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_266 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_267 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_268 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_269 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_270 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_271 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_272 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_273 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_274 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_275 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_276 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_277 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_278 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_279 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_280 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_281 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_282 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_283 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_284 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_285 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_286 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_287 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_288 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_289 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_290 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_291 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_292 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_293 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_294 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_295 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_296 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_297 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_298 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_299 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_300 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_301 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_302 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_303 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_304 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_305 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_306 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_307 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_308 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_309 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_310 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_311 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_312 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_313 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_314 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_315 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_316 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_317 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_318 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_319 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_320 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_321 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_322 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_323 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_324 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_325 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_326 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_327 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_328 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_329 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_330 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_331 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_332 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_333 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_334 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_335 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_336 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_337 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_338 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_339 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_340 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_341 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_342 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_343 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_344 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_345 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_346 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_347 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_348 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_349 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_350 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_351 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_352 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_353 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_354 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_355 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_356 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_357 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_358 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_359 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_360 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_361 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_362 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_363 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_364 border p-1.5 w-1 rounded-sm "></div>
                    <div className="_365 border p-1.5 w-1 rounded-sm "></div>
                    </div>
                    <div className='flex justify-center items-center gap-1'>
                        <div>colors :</div>
                        <div className="border p-1.5 w-1 rounded-sm bg-green-0"></div>
                        <div className="border p-1.5 w-1 rounded-sm bg-green-300 "></div>
                        <div className="border p-1.5 w-1 rounded-sm bg-green-400 "></div>
                        <div className="border p-1.5 w-1 rounded-sm bg-green-600 "></div>
                        <div className="border p-1.5 w-1 rounded-sm bg-green-800 "></div>
                    </div>
                </div>
                <div className='border'>
                    <div className='text-center p-2 flex gap-1 justify-center items-center'>
                        <button className='border p-1 px-3 rounded-sm bg-linear-90 from-blue-400 to-cyan-400 active:scale-105'>show</button>
                        <button className='border p-1 px-3 rounded-sm bg-linear-90 from-sky-300 to-cyan-400 active:scale-105'>reset</button>
                    </div>
                    <div className="datasetshowandchangebox p-1">
                        <div className="border"></div>
                    </div>
                </div>
            </section>
        </>
    )
}

export default Landing5